name: Bob 

on: [push]
jobs:
  Explore-Bob:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.linux-svg-2D }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Call haskell Stack
        run: ghci -e "main" -interactive-print=FileSystem2.main fileSystem2
      - name: Some Linux script
        uses: actions/checkout@v3 
      - run: echo "ğŸ–¥ï¸ Enter a number.",
             read VAR,
             if [[ $VAR -gt 10 ]],
             then,
               echo "The variable is greater than 10.",
             fi
